/* 
    File: RecordsView.java
    Project: COSC-4360 Capstone Project Team #0
    University: McMurry University
    Course: COSC–4360 Spring 2021
    Instructor: Mr. Brozovic
    Programmer: Jacob Bremiller
    Created by: Stephen Dunn
    Created: 2/01/2021
    Updated by: Jacob Bremiller
    Updated: 3/3/2021
    Compiler: Apache NetBeans IDE for Java SE
    Description: Contains buttons to generate the records
 */
package chocanon.Views;

import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author smdun
 */
public class RecordsView extends javax.swing.JFrame {

    /**
     * Creates new form Records
     */
    public RecordsView() {
        initComponents();
    }
    
    //Setters
    public void setRecordsBackButtonListener(ActionListener e){
        btn_RecordsBack.addActionListener(e);
    }
    public void setRecordsServiceRecordsButtonListener(ActionListener e){
        btn_servicerecords.addActionListener(e);
    }
    public void setRecordsEftRecordsButtonListener(ActionListener e){
        btn_eftrecords.addActionListener(e);
    }
    
    //Methods
    public void showMessageBox(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    
    public String[] getFromAndToDate(String startDate, String endDate){
      final DatePickerSettings startDateSettings = new DatePickerSettings();
      final DatePickerSettings endDateSettings = new DatePickerSettings();
      startDateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
      endDateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
      
      final DatePicker startDatePicker = new DatePicker(startDateSettings);
      final DatePicker endDatePicker = new DatePicker(endDateSettings);
      
      startDatePicker.getComponentDateTextField().setEditable(false);
      endDatePicker.getComponentDateTextField().setEditable(false);
      
      if(startDate.equals("") != true){
        startDatePicker.setDate(LocalDate.parse(startDate));
      }
      if(endDate.equals("") != true){
        endDatePicker.setDate(LocalDate.parse(endDate));
      }
      
      //Create panel
      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Start Date:"));
      myPanel.add(startDatePicker);
      myPanel.add(Box.createHorizontalStrut(15));
      myPanel.add(new JLabel("End Date:"));
      myPanel.add(endDatePicker);
      
      int result = JOptionPane.showConfirmDialog(null, myPanel, "Please enter start and end date.", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
            return new String[]{startDatePicker.getText(),endDatePicker.getText()};
      }
      return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_servicerecords = new javax.swing.JButton();
        btn_eftrecords = new javax.swing.JButton();
        lbl_records = new javax.swing.JLabel();
        btn_RecordsBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Records");
        setResizable(false);

        btn_servicerecords.setText("Generate Service Records");

        btn_eftrecords.setText("Generate EFT Records");

        lbl_records.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_records.setText("Records");

        btn_RecordsBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/go-back-left-arrow.png"))); // NOI18N
        btn_RecordsBack.setBorderPainted(false);
        btn_RecordsBack.setContentAreaFilled(false);
        btn_RecordsBack.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_RecordsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(lbl_records))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_eftrecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_servicerecords, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_RecordsBack)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_records, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_servicerecords, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_eftrecords, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_RecordsBack;
    private javax.swing.JButton btn_eftrecords;
    private javax.swing.JButton btn_servicerecords;
    private javax.swing.JLabel lbl_records;
    // End of variables declaration//GEN-END:variables
}
