/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocanon;

/* 
    File: ServiceForm.java
    Project: COSC-4360 Capstone Project Team #0
    University: McMurry University
    Course: COSC–4360 Spring 2021
    Instructor: Mr. Brozovic
    Programmer: Jacob Bremiller
    Created by: Jacob Bremiller
    Created: 2/20/2021
    Updated by: Jacob Bremiller
    Updated: 2/20/2021
    Compiler: Apache NetBeans IDE for Java SE
    Description: Contains the service form information
 */
public class ServiceForm extends javax.swing.JFrame {

    /**
     * Creates new form ServiceForm
     */
    public ServiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_MemberName = new javax.swing.JLabel();
        lbl_MemberNumber = new javax.swing.JLabel();
        lbl_CurrDateTime = new javax.swing.JLabel();
        lbl_DateOfService = new javax.swing.JLabel();
        lbl_ServiceCode = new javax.swing.JLabel();
        txt_MemberName = new javax.swing.JTextField();
        txt_MemberNumber = new javax.swing.JTextField();
        txt_CurrDateTime = new javax.swing.JTextField();
        txt_DateOfService = new javax.swing.JTextField();
        txt_ServiceCode = new javax.swing.JTextField();
        lbl_FeeToBePaid = new javax.swing.JLabel();
        btn_SubmitForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_MemberName.setText("Member Name");

        lbl_MemberNumber.setText("Member Number");

        lbl_CurrDateTime.setText("Current Date & Time");

        lbl_DateOfService.setText("Date Of Service");

        lbl_ServiceCode.setText("Service Code");

        txt_CurrDateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CurrDateTimeActionPerformed(evt);
            }
        });

        lbl_FeeToBePaid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_FeeToBePaid.setText("Fee To Be Paid $0.00");

        btn_SubmitForm.setText("Submit Form");
        btn_SubmitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_FeeToBePaid)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_CurrDateTime)
                            .addComponent(lbl_MemberNumber)
                            .addComponent(lbl_MemberName)
                            .addComponent(btn_SubmitForm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DateOfService)
                            .addComponent(lbl_ServiceCode)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_MemberName)
                                    .addComponent(txt_ServiceCode, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txt_MemberNumber)
                                    .addComponent(txt_CurrDateTime)
                                    .addComponent(txt_DateOfService))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_FeeToBePaid)
                .addGap(18, 18, 18)
                .addComponent(lbl_MemberName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_MemberNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_CurrDateTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_CurrDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_DateOfService)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DateOfService, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbl_ServiceCode)
                .addGap(10, 10, 10)
                .addComponent(txt_ServiceCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SubmitForm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SubmitFormActionPerformed

    private void txt_CurrDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CurrDateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CurrDateTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SubmitForm;
    private javax.swing.JLabel lbl_CurrDateTime;
    private javax.swing.JLabel lbl_DateOfService;
    private javax.swing.JLabel lbl_FeeToBePaid;
    private javax.swing.JLabel lbl_MemberName;
    private javax.swing.JLabel lbl_MemberNumber;
    private javax.swing.JLabel lbl_ServiceCode;
    private javax.swing.JTextField txt_CurrDateTime;
    private javax.swing.JTextField txt_DateOfService;
    private javax.swing.JTextField txt_MemberName;
    private javax.swing.JTextField txt_MemberNumber;
    private javax.swing.JTextField txt_ServiceCode;
    // End of variables declaration//GEN-END:variables
}
