/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProviderTerminal.Views;

/**
 *
 * @author ljcla
 */
public class ProvideAServiceMenu extends javax.swing.JFrame {

    /**
     * Creates new form ProvideAServiceMenu
     */
    public ProvideAServiceMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_SwipeMemberCard = new javax.swing.JButton();
        btn_ViewReports = new javax.swing.JButton();
        btn_TotalFees = new javax.swing.JButton();
        btn_RequestProviderDirectory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Provider Name");

        btn_SwipeMemberCard.setText("Swipe Member Card");
        btn_SwipeMemberCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SwipeMemberCardActionPerformed(evt);
            }
        });

        btn_ViewReports.setText("View Reports");

        btn_TotalFees.setText("Total Fees");
        btn_TotalFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TotalFeesActionPerformed(evt);
            }
        });

        btn_RequestProviderDirectory.setText("Request Provider Directory");
        btn_RequestProviderDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RequestProviderDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_RequestProviderDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TotalFees, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ViewReports, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SwipeMemberCard, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_SwipeMemberCard)
                .addGap(18, 18, 18)
                .addComponent(btn_ViewReports)
                .addGap(11, 11, 11)
                .addComponent(btn_TotalFees)
                .addGap(18, 18, 18)
                .addComponent(btn_RequestProviderDirectory)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SwipeMemberCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SwipeMemberCardActionPerformed
        this.setVisible(false);
        new SwipeMemberCard().setVisible(true);
    }//GEN-LAST:event_btn_SwipeMemberCardActionPerformed

    private void btn_TotalFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TotalFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TotalFeesActionPerformed

    private void btn_RequestProviderDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RequestProviderDirectoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RequestProviderDirectoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProvideAServiceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProvideAServiceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProvideAServiceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProvideAServiceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProvideAServiceMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_RequestProviderDirectory;
    private javax.swing.JButton btn_SwipeMemberCard;
    private javax.swing.JButton btn_TotalFees;
    private javax.swing.JButton btn_ViewReports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
