/* 
    File: ServiceFormView.java
    Project: COSC-4360 Capstone Project Team #0
    University: McMurry University
    Course: COSC–4360 Spring 2021
    Instructor: Mr. Brozovic
    Programmer: Jacob Bremiller
    Created by: Lydia Clarke
    Created: 2/02/2021
    Updated by: Jacob Bremiller
    Updated: 3/3/2021
    Compiler: Apache NetBeans IDE for Java SE
    Description: IDK
 */
package ProviderTerminal.Views;

/**
 *
 * @author ljcla
 */
public class ServiceFormView extends javax.swing.JFrame {

    /**
     * Creates new form ServiceFees
     */
    public ServiceFormView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_FeeToBePaid = new javax.swing.JLabel();
        lbl_MemberName = new javax.swing.JLabel();
        txt_MemberName = new javax.swing.JTextField();
        lbl_MemberNumber = new javax.swing.JLabel();
        txt_MemberNumber = new javax.swing.JTextField();
        lbl_CurrentDateTiime = new javax.swing.JLabel();
        txt_CurrentDateTime = new javax.swing.JTextField();
        lbl_DOS = new javax.swing.JLabel();
        txt_DOS = new javax.swing.JTextField();
        lbl_ServiceCode = new javax.swing.JLabel();
        txt_ServiceCode = new javax.swing.JTextField();
        btn_SubmitForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_FeeToBePaid.setText("Fee to be Paid: $100");

        lbl_MemberName.setText("Member Name");

        txt_MemberName.setText("John Doe");
        txt_MemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MemberNameActionPerformed(evt);
            }
        });

        lbl_MemberNumber.setText("Member Number");

        txt_MemberNumber.setText("123456789");

        lbl_CurrentDateTiime.setText("Current Date & Time");

        txt_CurrentDateTime.setText("MM-DD-YYYY HH:MM:SS");

        lbl_DOS.setText("Date of Service");

        txt_DOS.setText("MM-DD-YYYY");

        lbl_ServiceCode.setText("Service Code");

        txt_ServiceCode.setText("123456");

        btn_SubmitForm.setText("Submit Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_DOS)
                    .addComponent(lbl_CurrentDateTiime)
                    .addComponent(lbl_MemberNumber)
                    .addComponent(lbl_MemberName)
                    .addComponent(lbl_FeeToBePaid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MemberName)
                    .addComponent(txt_MemberNumber)
                    .addComponent(txt_CurrentDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(txt_DOS)
                    .addComponent(lbl_ServiceCode)
                    .addComponent(txt_ServiceCode)
                    .addComponent(btn_SubmitForm, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_FeeToBePaid)
                .addGap(18, 18, 18)
                .addComponent(lbl_MemberName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_MemberNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_CurrentDateTiime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_CurrentDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_DOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ServiceCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ServiceCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btn_SubmitForm)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MemberNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceFormView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SubmitForm;
    private javax.swing.JLabel lbl_CurrentDateTiime;
    private javax.swing.JLabel lbl_DOS;
    private javax.swing.JLabel lbl_FeeToBePaid;
    private javax.swing.JLabel lbl_MemberName;
    private javax.swing.JLabel lbl_MemberNumber;
    private javax.swing.JLabel lbl_ServiceCode;
    private javax.swing.JTextField txt_CurrentDateTime;
    private javax.swing.JTextField txt_DOS;
    private javax.swing.JTextField txt_MemberName;
    private javax.swing.JTextField txt_MemberNumber;
    private javax.swing.JTextField txt_ServiceCode;
    // End of variables declaration//GEN-END:variables
}
