/* 
    File: ServiceDetailsView.java
    Project: COSC-4360 Capstone Project Team #0
    University: McMurry University
    Course: COSC–4360 Spring 2021
    Instructor: Mr. Brozovic
    Programmer: Jacob Bremiller
    Created by: Lydia Clarke
    Created: 2/02/2021
    Updated by: Jacob Bremiller
    Updated: 3/3/2021
    Compiler: Apache NetBeans IDE for Java SE
    Description: Provides the a simulation of the provider bill chocan
 */
package ProviderTerminal.Views;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;

/**
 *
 * @author ljcla
 */
public class ServiceDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form ServiceForm
     */
    public ServiceDetailsView() {
        initComponents();
    }
    
    //Getters
    public String getServiceCodeTxt(){
        return txt_ServiceCode.getText();
    }
    
    //Setters
    public void setSubmitBillButtonListener(ActionListener e){
        btn_SubmitBill.addActionListener(e);
    }
    
    public void setServiceCodeTextListener(FocusListener e){
        txt_ServiceCode.addFocusListener(e);
    }
    
    public void setServiceCodeTxt(String serviceCode){
        txt_ServiceCode.setText(serviceCode);
    }
    
    public void setMessageLabel(String feedbackMessage, Color messageColor){
        lbl_FeedbackMessage.setForeground(messageColor);
        lbl_FeedbackMessage.setText(feedbackMessage);
    } 
    
    //Methods
    public void setFocusServiceCode(){
        txt_ServiceCode.requestFocus();
    } 
   
    public void setFocusAdditionalComments(){
        txt_AdditionalComments.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ServiceDetails = new javax.swing.JLabel();
        txt_DOS = new javax.swing.JTextField();
        lbl_DOS = new javax.swing.JLabel();
        lbl_ServiceCode = new javax.swing.JLabel();
        txt_ServiceCode = new javax.swing.JTextField();
        lbl_AdditionalComments = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_AdditionalComments = new javax.swing.JTextArea();
        btn_SubmitBill = new javax.swing.JButton();
        lbl_FeedbackMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_ServiceDetails.setText("Service Details");

        txt_DOS.setText("MM-DD-YYYY");

        lbl_DOS.setText("Date of Service ");

        lbl_ServiceCode.setText("Service Code");

        txt_ServiceCode.setText("123456");

        lbl_AdditionalComments.setText("Additional Comments");

        txt_AdditionalComments.setColumns(20);
        txt_AdditionalComments.setRows(5);
        jScrollPane1.setViewportView(txt_AdditionalComments);

        btn_SubmitBill.setText("Submit Bill");

        lbl_FeedbackMessage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_SubmitBill, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lbl_AdditionalComments)
                    .addComponent(txt_ServiceCode)
                    .addComponent(lbl_ServiceCode)
                    .addComponent(txt_DOS, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lbl_DOS)
                    .addComponent(lbl_ServiceDetails)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lbl_FeedbackMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbl_ServiceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_DOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DOS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ServiceCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ServiceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_AdditionalComments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_SubmitBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_FeedbackMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SubmitBill;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_AdditionalComments;
    private javax.swing.JLabel lbl_DOS;
    private javax.swing.JLabel lbl_FeedbackMessage;
    private javax.swing.JLabel lbl_ServiceCode;
    private javax.swing.JLabel lbl_ServiceDetails;
    private javax.swing.JTextArea txt_AdditionalComments;
    private javax.swing.JTextField txt_DOS;
    private javax.swing.JTextField txt_ServiceCode;
    // End of variables declaration//GEN-END:variables
}
