/* 
    File: ValidateServiceCodeView.java
    Project: COSC-4360 Capstone Project Team #0
    University: McMurry University
    Course: COSC–4360 Spring 2021
    Instructor: Mr. Brozovic
    Programmer: Jacob Bremiller
    Created by: Lydia Clarke
    Created: 2/02/2021
    Updated by: Jacob Bremiller
    Updated: 3/3/2021
    Compiler: Apache NetBeans IDE for Java SE
    Description: Provides a means to validate that the service code entered by the provider is correct.
 */
package ProviderTerminal.Views;

import java.awt.event.ActionListener;

/**
 *
 * @author ljcla
 */
public class ValidateServiceCodeView extends javax.swing.JFrame {

    /**
     * Creates new form ValidateServiceCode
     */
    public ValidateServiceCodeView() {
        initComponents();
    }

    //Setters
    public void setServiceCode(String serviceCode){
        lbl_ServiceCode.setText("Service Code: " + serviceCode);
    }
    public void setServiceName(String serviceName){
        lbl_ServiceName.setText("Service Name: " + serviceName);
    }
    
    public void setCorrectServiceCodeButtonListener(ActionListener e){
        btn_CorrectServiceCode.addActionListener(e);
    }
    public void setIncorrectServiceCodeButtonListener(ActionListener e){
        btn_IncorrectServiceCode.addActionListener(e);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ServiceCode = new javax.swing.JLabel();
        lbl_ServiceName = new javax.swing.JLabel();
        lbl_CheckCorrectService = new javax.swing.JLabel();
        btn_IncorrectServiceCode = new javax.swing.JButton();
        btn_CorrectServiceCode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_ServiceCode.setText("Service Code: 123456");

        lbl_ServiceName.setText("Service Name: Physical Therapy");

        lbl_CheckCorrectService.setText("Is this the Correct Service?");

        btn_IncorrectServiceCode.setText("No, Change service code");
        btn_IncorrectServiceCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IncorrectServiceCodeActionPerformed(evt);
            }
        });

        btn_CorrectServiceCode.setText("Yes, Continue");
        btn_CorrectServiceCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CorrectServiceCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_ServiceName, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(lbl_ServiceCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lbl_CheckCorrectService))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_CorrectServiceCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_IncorrectServiceCode, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbl_ServiceCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ServiceName)
                .addGap(35, 35, 35)
                .addComponent(lbl_CheckCorrectService)
                .addGap(18, 18, 18)
                .addComponent(btn_CorrectServiceCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_IncorrectServiceCode)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IncorrectServiceCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IncorrectServiceCodeActionPerformed

    }//GEN-LAST:event_btn_IncorrectServiceCodeActionPerformed

    private void btn_CorrectServiceCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CorrectServiceCodeActionPerformed

    }//GEN-LAST:event_btn_CorrectServiceCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidateServiceCodeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidateServiceCodeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidateServiceCodeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidateServiceCodeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidateServiceCodeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CorrectServiceCode;
    private javax.swing.JButton btn_IncorrectServiceCode;
    private javax.swing.JLabel lbl_CheckCorrectService;
    private javax.swing.JLabel lbl_ServiceCode;
    private javax.swing.JLabel lbl_ServiceName;
    // End of variables declaration//GEN-END:variables
}
